---
title: "**GNN-EGG**: Graph Neural Network Explanations *via* Graph Generation"
author: "Art Tay"
format:
  pdf: 
     documentclass: article
     papersize: letter
     geometry:
         margin=1in
     include-in-header: header.tex
  docx: default 
bibliography: references.bib
highlight-style: github
---

# Abstract 

\begin{center}
Keywords: Graph Neural Networks, Interpretable AI 
\end{center}

# Introduction 

# Related Work

# Preliminaries

## Formal Definition of Generative Explanations

Let the observed data be $(Y, X)$, where $Y$ is a class label or probability 
vector for classes, and $X$ is a collection of corresponding features.
Conventionally $Y$ is assumed to be a random variable and $X$ is fixed. 
We are typically interested in model the distribution of $Y \ | \ X$.  
Here we will assume the model takes the form of 
\begin{equation}
    f(Y \ | \ X) \approx g(X; \hat \beta) + \epsilon = \hat y 
\end{equation}
where $\epsilon$ is the prediction error. Usually the focus of interpretation 
of this type of model if the distribution of $\hat \beta$, or the marginal 
effects of $X$ on $Y$. In many cases $g$ is far to complex to derive clear 
marginal effects, and interval estimates come at the cost of strong 
parametric assumptions. Furthermore, the effects are ordinarily analyzed 
independently; however, we would argue that this paradigm fails when $X$ has a 
complex structure. For example, in image analysis, $\hat \beta$ estimates on 
pixel values we do very little to help understand the model overall prediction 
for the image. 

We suggest that when $g$ and $X$ are complicated, researchers ought 
to use generative explanations. Formally, this means assuming $X$ is a 
random variable and attempting to model the distribution of $X \ | \ Y$.
This is generally done using a model of the form: 
\begin{equation}
    f(X \ | \ Y) \approx h(Z; \Omega) + \epsilon = \hat X
\end{equation}
where $Z$ is random noise. Given a fit model $\hat g$, estimation $h$ can be 
done using: 
\begin{equation} 
    \underset{\hat \Omega}{\text{argmax}} \ \ \hat g(h(z; \Omega); \hat \beta)
\end{equation}
where $\hat g$ here is assumed to return the probability of being a member of 
the target class. 

Generative explanation have 3 key advantages: 

1. They incorporate information from all the observed instances as well as the 
fit model.  

2. Modeling a distribution allows for easy interval and uncertainty estimation.   

3. The explanations are within the same domain as the data, which may be more 
readily interpretable than marginal effects. 

# Methodology 

## Notation

Let $G$ be a graph with $X$, $E$, and $A$ being 
the node feature matrix, edge feature matrix, and adjacency 
matrix respectively. Let $X = [X_c, X_d]$ and $E = [E_c, E_d]$
where $c$ and $d$ denote continuous and one-hot discrete features. 

## Generation

$X_c$ and $E_c$ can both be sampled from any function with the form:
\begin{equation}
    f(z\ ; \ \Omega): \mathbb{R}^Z \to \mathbb{R}^{dim}
\end{equation}
and $dim$ denotes the dimensionality of the matrix we want to generate. $z$ 
could be sampled as pure random noise, but $z$ could also be a function 
of the data. In most instances, we generate continuous feature matrices 
using a random vector from a multivariate normal pass through a standard
dense layer with no activation.

$X_d$ and $E_d$ can both be sampled from the 
*concrete distribution* [@Maddison_Mnih_Teh_2017].
Using the reparameterization trick and continuous relaxation, we 
can sample one-hot categorical vectors based on two parameters 
$\theta_{\text{Cat}}$, a trainable parameter vector of length equal to 
the number of categories, and $\tau$, a hyperparameter that controls 
the degree of relaxation (smaller value approximate the discrete 
sampling better, but can result in numerical issues). 
\begin{equation}
    \text{Softmax}
    \left(
        \dfrac{\theta - log(-log \ \epsilon)}{\tau}
    \right), \quad \epsilon \sim U[0, 1]
\end{equation}
Like $z$, $\theta_{\text{Cat}}$ could be a function of the data and other 
trainable parameters. One concrete distribution would be required per 
discrete feature.  

Similarly, the adjacency matrix can be sampled from the *binary concrete 
distribution*:
\begin{equation}
    \text{sigmoid}
        \left(\dfrac{\theta + \log \ \epsilon - \log(1 - \log \ \epsilon)}{\tau} \right)
\end{equation}
Identical to [@Wang_Shen_2023], set $\theta$ to be the same 
dimensionality as $A$, where each entry in $\theta$ is the probability 
that an edge exists between nodes $i$ and $j$. 

Pseudo-code for a generic *egg* generator is provided below. 
```{r}
#| eval: false
generator(z_1, z_2, theta_1, theta_3, theta_3, tau_1, tau_2, tau_3){
    X_c = f(z_1; Omega_1)

    E_c = f(z_2; Omega_2)

    for each discrete node feature i do:
        X_di ~ concrete_1(theta_1i, tau_1)
        X_d = [X_d, X_di]

    for each discrete edge feature i do:
        E_di ~ concrete_1(theta_2i, tau_2)
        E_d = [E_d, E_di]

    A ~ binary_concrete(theta_3, tau_3) 

    return X_c, X_d, E_c, E_d, A
}
```

## Loss Function 

*GNN-EGG* trains based on a three part loss function. 

### GNN Prediction & Embedding Loss 

Let `explainee()` be the GNN model we want to explain. Let 
$g()$ represent the embedding layers and $h()$ represent 
the dense predictions layers. $g()$ is assumed to return a vectorization 
of a graph, and $h()$ is assumed to return a class probability vector. 
\begin{equation}
    \mathcal{L}_p = \text{distance}(g(G), \psi) + 
        \text{Cross-Entropy}(h(g(G)), t)
\end{equation}
$t$ denotes the desired prediction, and $\psi$ can either be the 
average embedding for the target class, like @Wang_Shen_2023 or 
a particular observation.

Most GNN `explainee` model will require further discretization of the 
`generator`'s output. The typically transformation are 
$A' = I(A \geq 0.5)$, $X_d = \text{argmax}(X_d)$, 
$E_c = \text{argmax}(E_c)$; however, each one will prevent
gradient backpropagation with respect to their corresponding 
parameters. This issue can be mitigated in two ways. First, the 
remaining two loss function terms do not involve the `explainee` 
directly and are designed to use the `generator` output without 
transformation [Discuss edge weights here]. 
Second, a REINFORCE [@Williams_1992] term can be added based on 
the likelihood of the generating distributions. For example if the $A'$ 
transformation is required, for following term can be added to ensure 
training of the edge probabilities.  
\begin{equation}
\mathbfcal{L}_{R} = -\dfrac{l(\theta_A \ | \ G)}{\mathcal{L}}
\end{equation} 
Here $\mathcal{L}$ denotes the sum of all other loss terms and 
$l$ denotes the log-likelihood. In short, this term moves $\theta_A$ to move
the likelihood of $G$ proportional to the inverse of the loss ie if 
$\mathcal{L}(G)$ is small, $\theta_A$ will be moved to increase the 
likelihood of $G$ and vice-a-versa.

### Regularization & Sparsity

Regularization the probability of edges existing will increase sparsity in terms 
of edges, and nodes if we remove any that become *isolated*. Identical to 
the regularization done in @Wang_Shen_2023, we add the following term. 
\begin{equation}
\mathcal{L}_s = ||\theta_A||^2 + \text{softplus}(||\text{sigmoid}||_1 - B)^2
\end{equation}
$B$ here is usually called the budget. It represents a ceiling on the number 
of edges that we desire on generated examples. 

### Structural Consistency Loss

Structurally consistency is the hardest to train, but arguable the most 
important property for an example to have. Most GNN use a message passing 
paradigm followed by pooling and dense prediction layers. The idea is to 
use the graph's structure to engineer better node features to draw 
predictions. This principle exposes a flaw in the generation scheme. 
If the generator is allowed to train the node features directly, it becomes 
likely that the generator will ignore the graph structure and leap to training 
the final features needed instead.

[A good example of this happening is that a model training only the 
node features, with all else random, was able to produce and 
incredible tight prediction distribution. This could also be done in 
spite of extreme regularization.]

Using embeddings in addition to the prediction can mitigate this problem; 
however, it is possible that embeddings could also be subject to this problem. 
For large graphs, there is a considerable amount of information that can be 
unrepresented in the latent vector. Two graphs could be very different on the 
graph level, but have very similar embeddings [include example?]. 
Furthermore, measurements of similarity of the latent space aren't readily 
interpretable by humans making is harder to evaluate and compare the realism of 
the generated data. Another proposed solution is to evaluate the reconstruction 
using a discriminator [@De_Cao_Kipf_2022]. While more interpretable than 
metrics on the latent space, discriminators suffer from the issue of 
non-identifiability. In other words, a desirable misclassification rate 
could be the result of a poor discriminator instead of a good generator.

Our proposed solution is to use an approximation to the graph edit distance (GED). 
GED measures the similarity between two graphs by counting the minimum number 
of edits required to make the graphs isomorphic (or subgraph isomorphic). 
This has the advantage of being human interpretable. [Ex: Being able to say that 
10 out of 100 nodes and edges need to be edit for the graphs to be identical
(ie the graph match 90%)
should be more informative than a cosine distance in the latent space for 
most applications.] Problematically, finding the exact optimal GED is a known 
NP-complete problem, which makes it infeasible for large graph or complex 
training algorithms [@Bougleux_Brun_Carletti_Foggia_Gaüzère_Vento_2015]. 
Furthermore, most exact algorithm aren't differentiable, which would 
necessitate slower optimization methods. Fortunately, approximating GED as a 
quadratic assignment problem (QAP) solves before the complexity and derivative 
issue [@wang2024pygm]. 



# Results 

# Notes/Ideas/Future Directions

## Graph Sub-Sampling Methods

"GraphSAINT follows the design philosophy of directly sampling the training graph G, rather than the corresponding GCN. Our goals are to 1. extract appropriately connected subgraphs so that little information is lost when propagating within the subgraphs, and 2. combine information of many subgraphs together so that the training process overall learns good representation of the full graph" [@Zeng_Zhou_Srivastava_Kannan_Prasanna_2020].

## Graph Sub-Sampling + Inverse Weighting 

Let $[G_1, \dots, G_n]$ be the set of observed graphs. Let $G_{s(i, j)}$ 
denote the $j^{th} \in [1, \dots, m]$ sub-sample of the 
$i^{th} \in [1, \dots, n]$ observed graph. 
Let $G_{g(i, j)}$ represent the corresponding generated graph. 
Let $\text{explainee}(G) = \rho, \ h$ denote the prediction and embedding 
vectors respectively. Let $\rho_t$ denote the prediction vector of the 
target class and $\rho_u$ denote an *uninformative* prediction. 

\begin{align}
    \gamma &= \text{CrtEnt}(\rho_t, \ \rho_u) \in [0, \infty) \\  
    \omega &= 
        \begin{cases} 
            \dfrac{\lambda_1}{\gamma - 
            \text{CrtEnt}(\rho_t, \ \rho_{s(i, j)})} 
            , \ \ &\text{ if } 
                \gamma = \text{CrtEnt}(\rho_t, \ \rho_{s(i, j))} \\ 
            -c \cdot \lambda_1, \ \ &\text{ otherwise.}
        \end{cases} \\ 
    \mathcal{L}_{\text{dist}} &= \dfrac{1}{nm} \sum_{i=1}^n \sum_{j=1}^m
        \text{dist}(h_{s(i, j)}, \ h_{g(i, j)}) + 
        \text{match}(G_{s(i, j)}, \ G_{g(i, j)}) 
\end{align}

- If the sub-graph prediction $\rho_{s(i, j)}$ is better than the 
uninformative prediction, then 
$$
\text{CrtEnt}(\rho_t, \rho_{s(i,j)}) < \gamma \Rightarrow
    \omega \geq 0 \Rightarrow \text{argmin} \ \mathcal{L}_{\text{dist}}
$$

- If the sub-graph prediction is worse than the uninformative prediction, then 
$$
\text{CrtEnt}(\rho_t, \rho_{s(i,j)}) > \gamma \Rightarrow
    \omega < 0 \Rightarrow \text{argmax} \ \mathcal{L}_{\text{dist}}
$$

**Potential Advantages:**

1. Solves the large graph memory issue. 
2. Creates more training samples. 
Sub-sampling and observed graphs don't have to be split be class.  
3. Weights the samples based on the models confidence. 
4. Moves the generator towards good samples and away from bad samples.  

**Potential Disadvantages:** 

1. Selection bias. 
2. Information loss.  

## Best Sub-Graph Match for Visualization

Let $G$ be an observed graph. Let $[G_{s1} \dots G_{sm}]$ be the set of 
sub-graph samples taken from graph $G$. Let $G_g$ be a generated explanation 
graph. Then, 
$$
\text{match}(G, G_g) \approx 
    \max \ \{\text{match}(G_g, \ G_{si}) \ | \ i \in [1, \ m] \}
$$

## Future Directions

- Generate graph with $\rho_u$ as the target. Analyze generated graphs that 
the model is most unsure about ie what are the model's weaknesses. 

- Tighten the generator distribution. Within a given batch select the generated 
graph with the best score (lowest loss so far), then add a matching loss term 
between all other generated graphs and the best one. 

# References 
