services:

  devcontainer: 
    build: 
      # Only includes current directory in build context. Keep as small possible. 
      # Use .dockerignore if big files in to be kept in .devcontainer/. 
      context: ..  
      dockerfile: .devcontainer/dockerfile

    volumes:
      # Mount the local repo folder to a repo folder in the container. 
      - ../:/repo

    shm_size: "64g"

    environment: 
      - RAY_memory_usage_threshold=0.99
      - RAY_memory_monitor_refresh_ms=0

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    stdin_open: true # Keep the standard input available even if the terminal is closed.  
    tty: true # Better interactive terminal sessions. 