# Base Image  
FROM nvidia/cuda:12.6.0-cudnn-runtime-ubuntu22.04

# Linux environment variables. 
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Install linux tools. 
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        build-essential git curl vim dpkg dos2unix \
        graphviz \
        bzip2 ca-certificates unzip fontconfig locales && \
    locale-gen en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 && \ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* 

# Install Oh My Posh. 
RUN curl -s https://ohmyposh.dev/install.sh | bash -s && \
    echo 'eval "$(oh-my-posh init bash --config 'https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/atomic.omp.json')"' >> ~/.bashrc && \
    echo 'alias ll="ls -lah"' >> ~/.bashrc

# Install uv. 
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

# uv settings.
ENV UV_PROJECT_ENVIRONMENT=/opt/venv
ENV UV_LINK_MODE=copy

# Build uv venv from lock file. 
COPY pyproject.toml uv.lock .python-version ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen
RUN echo '. ../../opt/venv/bin/activate' >> ~/.bashrc

# Set Git user configuration.
RUN git config --global user.name "container" && \
    git config --global user.email "container@docker.com"

# Resolves tidymodels incorrect time zone warning
RUN mkdir -p /var/db/timezone
RUN ln -sf /usr/share/zoneinfo/Etc/UTC /var/db/timezone/localtime

# Set working directory name. 
WORKDIR /repo

# Copy current directory. 
COPY . /repo/